### ISSUE TITLE
[Request] Add kg/cm² to psi

### ISSUE THREAD

**Issue by cemetary** [doug-101/ConvertAll-py#13]
1 kg/cm² → 14.223343334284860736 psi
1 psi → 0.070306957829636 kg/cm²

**Comment by doug-101** [comment]
Pressure is defined as a force per unit area.  A kilogram is generally a mass unit, not a force unit.  There is a "kilogram force" unit, abbreviated "kgf", that is the equivalent force unit.  So the conversion you want already woks in ConvertAll if entered as "kgf/cm^2".

-Doug

**Comment by cemetary** [comment]
I _really_ had that feeling that I had seen it (and use it) before. But since I couldn't find it because of my mistake (confusing "kg" for "kgf"), I thought it was my mind just playing games.

Anyway, thank you very much. :-)
