### ISSUE TITLE
Can we add Ft3 to Kwh

### ISSUE THREAD

**Issue by zizwiz** [doug-101/ConvertAll-py#22]
In UK the price of gas has shot up. People now want to find out the cost of daily usage. Being UK many meters are old and read gas volume in ft cubed while prices are for kWh. The tool says these are not compatible, can you add them? I use ft3 * 31,51 = kWh. but there is the full formula available.

**Comment by doug-101** [comment]
Unfortunately, that conversion is not consistent.  They are comparing a volume measurement to an energy measurement.  The results would vary based on what the gas contained (methane, propane, etc.) and its energy density.
