### ISSUE TITLE
add thermal resistance

### ISSUE THREAD

**Issue by qlmackey** [doug-101/ConvertAll-py#4]
Great tool! I needed to convert R-Value to RSI and vice verse so thought I would send the code along in case you wanted to add it to future distros 

```
#
# thermal resistance
#
[thermal resistance]
RV                           = R*ft^2*hr/Btu
rvalue                       = RV
rvalue systeme international = m^2*K/W
rsi                          = rvalue systeme international
```

**Comment by doug-101** [comment]
Thanks for the suggestion.  I'll add it to the next release (but it may not be soon).

**Comment by doug-101** [comment]
Done, in git
