### ISSUE TITLE
Converting 32F to 0C

### ISSUE THREAD

**Issue by qlmackey** [doug-101/ConvertAll-py#5]
Found a fun bug

From Unit: F
To Unit: C

if I enter 32 F I get  5.6843419E-14 C

![image](https://user-images.githubusercontent.com/5314446/52448063-2a769980-2adf-11e9-8048-da05d97db766.png)

but if I enter
From Unit: C
To Unit: F

entering 0C I get 32F

![image](https://user-images.githubusercontent.com/5314446/52448101-4712d180-2adf-11e9-9875-e5c4ed3a68e7.png)

**Comment by doug-101** [comment]
Not really a bug, just a consequence of computers calculating in binary without perfect precision.

You have to admit that 10^-14 is very, very close to zero.

Unfortunately, the application has no way of knowing what answers are legitimate small numbers and which should be rounded to a more appropriate answer.
