### ISSUE TITLE
[Enhancement] Add Hartree (Ha) and Rydberg (Ry) energy unit

### ISSUE THREAD

**Issue by augstb** [doug-101/ConvertAll-py#6]
Suggestion :
Can you just please add the Hartree energy (Ha) unit as well as Rydberg (Ry) that are commonly used in condensed matter physics ?

https://en.wikipedia.org/wiki/Hartree
https://en.wikipedia.org/wiki/Rydberg_constant

Thank you very much !

**Comment by doug-101** [comment]
Done, in git.
